services:
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    environment:
      - BACKEND_SERVER_BASENAME=https://backend.monitor.gveloso.com
    ports:
      - 4000:443
    depends_on:
      - php
    restart: unless-stopped
  php:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/var/www/html
      - ./worker/:/var/www/html/db
    ports:
      - 8080:80
    restart: unless-stopped
